name = "cf-docker-proxy"
compatibility_date = "2023-12-01"
main = "src/index.ts"

[vars]
CUSTOM_DOMAIN = "example.com"
TARGET_UPSTREAM = "https://registry-1.docker.io"
MODE = "production"

[observability]
enabled = true
head_sampling_rate = 1
